
from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                                "parsers", "python"))

NS = "http://fucaspark.com/aodm/1.2"
VOCAB = NS + "#"
BASE_IRI = "https://fucaspark.com/aodm/instance/"

@dataclass
class Node:
    id: str
    labels: List[str]
    props: Dict[str, Any] = field(default_factory=dict)

@dataclass
class Edge:
    source: str
    target: str
    type: str
    props: Dict[str, Any] = field(default_factory=dict)

@dataclass
class Graph:
    nodes: List[Node] = field(default_factory=list)
    edges: List[Edge] = field(default_factory=list)

    def node(self, node_id: str) -> Optional[Node]:
        for n in self.nodes:
            if n.id == node_id:
                return n
        return None

    def summary(self) -> str:
        by_label: Dict[str, int] = {}
        for n in self.nodes:
            by_label[n.labels[0]] = by_label.get(n.labels[0], 0) + 1
        by_type: Dict[str, int] = {}
        for e in self.edges:
            by_type[e.type] = by_type.get(e.type, 0) + 1

        lines = [f"{len(self.nodes)} nodes, {len(self.edges)} edges", "", "Nodes"]
        for k, v in sorted(by_label.items()):
            lines.append(f"  {v:4}  {k}")
        lines.append("")
        lines.append("Edges")
        for k, v in sorted(by_type.items()):
            lines.append(f"  {v:4}  {k}")

        neg = [e for e in self.edges if e.props.get("polarity") == "negative"]
        if neg:
            lines += ["", f"{len(neg)} NEGATIVE edge(s) — these assert something is known "
                          "FALSE and must not be traversed as positive:"]
            for e in neg:
                lines.append(f"  {e.source} -[NOT {e.type}]-> {e.target}")
        return "\n".join(lines)

    def to_json(self, indent: int = 2) -> str:
        return json.dumps({
            "nodes": [{"id": n.id, "labels": n.labels, **n.props} for n in self.nodes],
            "edges": [{"source": e.source, "target": e.target, "type": e.type, **e.props}
                      for e in self.edges],
        }, indent=indent, ensure_ascii=False)

    def to_cypher(self) -> str:
        out = ["// AODM 1.2 graph — generated by aodm_graph.py",
               "// Safe to re-run: MERGE will not duplicate nodes or edges.",
               ""]
        for n in self.nodes:
            labels = ":".join(n.labels)
            props = _cypher_props({"id": n.id, **n.props})
            out.append(f"MERGE (n:{labels} {{id: {_cypher_val(n.id)}}}) SET n += {props};")
        out.append("")
        for e in self.edges:
            props = _cypher_props(e.props)
            setter = f" SET r += {props}" if e.props else ""
            out.append(
                f"MATCH (a {{id: {_cypher_val(e.source)}}}), (b {{id: {_cypher_val(e.target)}}}) "
                f"MERGE (a)-[r:{e.type}]->(b){setter};"
            )
        return "\n".join(out)

    def to_turtle(self) -> str:
        out = [f"@prefix aodm: <{VOCAB}> .",
               f"@prefix inst: <{BASE_IRI}> .",
               "@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .",
               "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
               ""]
        for n in self.nodes:
            subject = f"inst:{_iri_safe(n.id)}"
            lines = [f"a aodm:{n.labels[0]}"]
            for k, v in n.props.items():
                if v in (None, "", []):
                    continue
                pred = "rdfs:label" if k == "label" else f"aodm:{_iri_safe(k, lower=True)}"
                lines.append(f"{pred} {_ttl_val(v)}")
            out.append(f"{subject}\n    " + " ;\n    ".join(lines) + " .")
            out.append("")

        for e in self.edges:
            s, o = f"inst:{_iri_safe(e.source)}", f"inst:{_iri_safe(e.target)}"
            pred = f"aodm:{_iri_safe(e.type, lower=True)}"
            if e.props:

                stmt = f"inst:stmt-{_iri_safe(e.source)}-{_iri_safe(e.type, lower=True)}-{_iri_safe(e.target)}"
                out.append(f"{s} {pred} {o} .")
                lines = ["a rdf:Statement",
                         f"rdf:subject {s}", f"rdf:predicate {pred}", f"rdf:object {o}"]
                for k, v in e.props.items():
                    if v in (None, "", []):
                        continue
                    lines.append(f"aodm:{_iri_safe(k, lower=True)} {_ttl_val(v)}")
                out.append(f"{stmt}\n    " + " ;\n    ".join(lines) + " .")
                out.append("")
            else:
                out.append(f"{s} {pred} {o} .")

        if any(e.props for e in self.edges):
            out.insert(3, "@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .")
        return "\n".join(out)

    def to_graphml(self) -> str:
        keys: Dict[str, str] = {}
        for n in self.nodes:
            for k in n.props:
                keys.setdefault(("n", k), f"dn{len(keys)}")
        edge_keys: Dict[str, str] = {}
        for e in self.edges:
            for k in e.props:
                edge_keys.setdefault(k, f"de{len(edge_keys)}")

        out = ['<?xml version="1.0" encoding="UTF-8"?>',
               '<graphml xmlns="http://graphml.graphdrawing.org/xmlns">',
               '  <key id="lbl" for="node" attr.name="label" attr.type="string"/>',
               '  <key id="etype" for="edge" attr.name="type" attr.type="string"/>']
        node_keys = {}
        for (_, k), kid in keys.items():
            node_keys[k] = kid
            out.append(f'  <key id="{kid}" for="node" attr.name="{_xml_esc(k)}" attr.type="string"/>')
        for k, kid in edge_keys.items():
            out.append(f'  <key id="{kid}" for="edge" attr.name="{_xml_esc(k)}" attr.type="string"/>')
        out.append('  <graph id="aodm" edgedefault="directed">')

        for n in self.nodes:
            out.append(f'    <node id="{_xml_esc(n.id)}">')
            out.append(f'      <data key="lbl">{_xml_esc(n.labels[0])}</data>')
            for k, v in n.props.items():
                if v in (None, "", []):
                    continue
                out.append(f'      <data key="{node_keys[k]}">{_xml_esc(_flat(v))}</data>')
            out.append("    </node>")

        for i, e in enumerate(self.edges):
            out.append(f'    <edge id="e{i}" source="{_xml_esc(e.source)}" target="{_xml_esc(e.target)}">')
            out.append(f'      <data key="etype">{_xml_esc(e.type)}</data>')
            for k, v in e.props.items():
                if v in (None, "", []):
                    continue
                out.append(f'      <data key="{edge_keys[k]}">{_xml_esc(_flat(v))}</data>')
            out.append("    </edge>")

        out += ["  </graph>", "</graphml>"]
        return "\n".join(out)

    def to_dot(self) -> str:
        shapes = {"Entity": "box", "Fact": "ellipse", "Rule": "diamond", "Source": "note"}
        out = ["digraph AODM {", '  rankdir=LR;', '  node [fontname="Helvetica" fontsize=10];',
               '  edge [fontname="Helvetica" fontsize=9];', ""]
        for n in self.nodes:
            label = n.props.get("label") or n.props.get("statement") or n.id
            label = _flat(label)
            if len(label) > 40:
                label = label[:37] + "..."
            shape = shapes.get(n.labels[0], "box")
            out.append(f'  "{_dot_esc(n.id)}" [label="{_dot_esc(label)}" shape={shape}];')
        out.append("")
        for e in self.edges:
            lbl = e.type
            style = ""
            if e.props.get("polarity") == "negative":
                lbl = "NOT " + lbl
                style = ' color="red" style=dashed'
            elif e.type in ("PREMISE", "CONCLUDES", "DERIVED_FROM"):
                style = ' style=dashed color="gray40"'
            conf = e.props.get("confidence")
            if conf is not None:
                lbl += f" ({conf})"
            out.append(f'  "{_dot_esc(e.source)}" -> "{_dot_esc(e.target)}" '
                       f'[label="{_dot_esc(lbl)}"{style}];')
        out.append("}")
        return "\n".join(out)

def _flat(v: Any) -> str:
    if isinstance(v, (list, tuple)):
        return " ".join(str(x) for x in v)
    if isinstance(v, dict):
        return json.dumps(v, ensure_ascii=False)
    return str(v)

def _iri_safe(s: str, lower: bool = False) -> str:
    out = re.sub(r"[^A-Za-z0-9_-]+", "-", str(s)).strip("-") or "x"
    return out.lower() if lower else out

def _xml_esc(s: Any) -> str:
    return (str(s).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))

def _dot_esc(s: Any) -> str:
    return str(s).replace("\\", "\\\\").replace('"', '\\"')

def _cypher_val(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(_cypher_val(x) for x in v) + "]"
    if isinstance(v, dict):
        return _cypher_props(v)
    return "'" + str(v).replace("\\", "\\\\").replace("'", "\\'") + "'"

def _cypher_props(d: Dict[str, Any]) -> str:
    parts = [f"{re.sub(r'[^A-Za-z0-9_]', '_', k)}: {_cypher_val(v)}"
             for k, v in d.items() if v not in (None, "", [])]
    return "{" + ", ".join(parts) + "}"

def _ttl_val(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (list, tuple)):
        return '"' + " ".join(str(x) for x in v) + '"'
    if isinstance(v, dict):
        return '"' + json.dumps(v, ensure_ascii=False).replace('"', '\\"') + '"'
    s = str(v)
    if re.match(r"^\d{4}-\d{2}-\d{2}$", s):
        return f'"{s}"^^xsd:date'
    if re.match(r"^\d{4}-\d{2}-\d{2}T", s):
        return f'"{s}"^^xsd:dateTime'
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'

def _rel_type(predicate: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", str(predicate)).strip("_").upper() or "RELATED_TO"

def compile_model(model: Dict[str, Any]) -> Graph:
    g = Graph()
    source_ids: Dict[str, str] = {}
    counters = {"fact": 0, "rule": 0, "rel": 0}

    def temporal(item: Dict[str, Any]) -> Dict[str, Any]:
        out = {}
        for k in ("valid_from", "valid_to"):
            if item.get(k):
                out[k] = item[k]
        return out

    def source_node(src: Dict[str, Any]) -> Optional[str]:
        if not isinstance(src, dict) or not src:
            return None
        key = src.get("uri") or src.get("title") or json.dumps(src, sort_keys=True)
        if key in source_ids:
            return source_ids[key]
        nid = "source-" + _iri_safe(key)[:60].lower()
        props = {k: v for k, v in src.items() if v not in (None, "")}
        g.nodes.append(Node(id=nid, labels=["Source"], props=props))
        source_ids[key] = nid
        return nid

    for e in model.get("entities", []):
        props: Dict[str, Any] = {}
        for k in ("type", "label", "content", "hash"):
            if e.get(k):
                props[k] = e[k]
        if e.get("confidence") is not None:
            props["confidence"] = e["confidence"]
        g.nodes.append(Node(id=e["id"], labels=["Entity"], props=props))

        sid = source_node(e.get("source"))
        if sid:
            g.edges.append(Edge(e["id"], sid, "SOURCED_FROM"))

    for r in model.get("relationships", []):
        counters["rel"] += 1
        props: Dict[str, Any] = {}
        if r.get("confidence") is not None:
            props["confidence"] = r["confidence"]

        props["polarity"] = r.get("polarity", "positive")
        props.update(temporal(r))
        if r.get("derived_from"):
            props["derived_from"] = r["derived_from"]
        if r.get("id"):
            props["aodm_id"] = r["id"]

        g.edges.append(Edge(r["subject"], r["object"], _rel_type(r.get("predicate")), props))

        sid = source_node(r.get("source"))
        if sid and r.get("id"):
            g.nodes.append(Node(id=r["id"], labels=["Relationship"],
                                props={"predicate": r.get("predicate")}))
            g.edges.append(Edge(r["id"], sid, "SOURCED_FROM"))

    for f in model.get("facts", []):
        counters["fact"] += 1
        fid = f.get("id") or f"fact-{counters['fact']}"
        props: Dict[str, Any] = {"statement": f.get("statement", "")}
        if f.get("confidence") is not None:
            props["confidence"] = f["confidence"]
        props["polarity"] = f.get("polarity", "positive")
        props.update(temporal(f))
        if f.get("hash"):
            props["hash"] = f["hash"]

        val = f.get("value")
        if isinstance(val, dict):

            for k in ("number", "min", "max", "tolerance", "unit"):
                if val.get(k) is not None:
                    props[f"value_{k}"] = val[k]

        g.nodes.append(Node(id=fid, labels=["Fact"], props=props))

        if f.get("about"):
            g.edges.append(Edge(fid, f["about"], "ABOUT"))

        sid = source_node(f.get("source"))
        if sid:
            g.edges.append(Edge(fid, sid, "SOURCED_FROM"))

        for ref in f.get("derived_from", []) or []:
            g.edges.append(Edge(fid, ref, "DERIVED_FROM"))

    for r in model.get("rules", []):
        counters["rule"] += 1
        rid = r.get("id") or f"rule-{counters['rule']}"
        props: Dict[str, Any] = {}
        if r.get("confidence") is not None:
            props["confidence"] = r["confidence"]
        props.update(temporal(r))
        g.nodes.append(Node(id=rid, labels=["Rule"], props=props))

        for cond in r.get("conditions", []) or []:
            ref = cond.get("ref") if isinstance(cond, dict) else cond
            pol = cond.get("polarity", "positive") if isinstance(cond, dict) else "positive"
            if ref:
                g.edges.append(Edge(rid, ref, "PREMISE", {"polarity": pol}))
        if r.get("conclusion"):
            g.edges.append(Edge(rid, r["conclusion"], "CONCLUDES"))

        sid = source_node(r.get("source"))
        if sid:
            g.edges.append(Edge(rid, sid, "SOURCED_FROM"))

    return g

def compile_file(path: str) -> Graph:
    from aodm import parse, parse_json
    text = open(path, "r", encoding="utf-8").read()
    doc = parse_json(text) if path.endswith(".json") else parse(text)
    return compile_model(doc.model)

FORMATS = {
    "cypher": "to_cypher", "turtle": "to_turtle", "ttl": "to_turtle",
    "graphml": "to_graphml", "dot": "to_dot", "json": "to_json",
}

def main(argv: List[str]) -> int:
    args = [a for a in argv[1:] if not a.startswith("-")]
    fmt = None
    for i, a in enumerate(argv):
        if a == "--format" and i + 1 < len(argv):
            fmt = argv[i + 1]
        elif a.startswith("--format="):
            fmt = a.split("=", 1)[1]
    args = [a for a in args if a != fmt]

    if not args:
        print(__doc__.strip().splitlines()[0], file=sys.stderr)
        print("usage: aodm_graph.py <file.xml|file.json> [--format "
              "cypher|turtle|graphml|dot|json]", file=sys.stderr)
        return 2

    try:
        g = compile_file(args[0])
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if not fmt:
        print(g.summary())
        return 0
    if fmt not in FORMATS:
        print(f"error: unknown format '{fmt}'. Choose from: "
              f"{', '.join(sorted(set(FORMATS)))}", file=sys.stderr)
        return 2

    print(getattr(g, FORMATS[fmt])())
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))
